{% set name = "encor" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/encor-{{ version }}.tar.gz
  sha256: 649bb2f830379722a8aff07d548f87acb9b2f11a320dde4cbd72364e07fa0dce

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - numpy
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - acor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davecwright3/acor
  dev_url: https://github.com/davecwright3/acor
  summary: Estimate the autocorrelation time of a time series quickly.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - davecwright3
