{% set name = "encor" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/encor-{{ version }}.tar.gz
  sha256: ab1dd9eeb9e9801816b3c59f8e5bd7d23e5d787387685051ead419818d435e40

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
    - wheel
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - acor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davecwright3/acor
  dev_url: https://github.com/davecwright3/acor
  summary: Estimate the autocorrelation time of a time series quickly.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - davecwright3
